version: '3.8'
services:
  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - db_data:/data/db
  bee:
    image: ethersphere/bee:stable
    ports:
      - '1633:1633'
    command:
      - dev
volumes:
  db_data:

